### PR TITLE
Accept all github urls

### PR DESCRIPTION
**Pull request by aurelijusrozenas**
Accept github urls that start with "git@github.com:".
Tag it `0.1` after merge please.

### CODE REVIEW

**Comment by kewlar** [comment]
Thanks for your interest! That was unexpected :)

I'm not maintaining this package anymore. I suggest you look into https://packagist.org/packages/pyrech/composer-changelogs instead – it solves the same problem and more, and is better maintained.

If you still want to go ahead with this PR, let me know, we'll work it out.

**Comment by aurelijusrozenas** [comment]
Yes, please merge this PR ;)

**Comment by aurelijusrozenas** [comment]
Please also tag 0.1 version.

**Comment by kewlar** [comment]
Done. Does it work for you?

**Pull request merged**
